config/routes.rb
BenGeocachingApp::Application.routes.draw do
  resources :tracks


  resources :geocaches


  authenticated :user do
    root :to => 'geocaches#index'
  end
  root :to => "home#index"
  devise_for :users
  resources :users
end

app/models/track.rb
class Track < ActiveRecord::Base
  attr_accessible :name
end

app/controllers/tracks_controller.rb
class TracksController < ApplicationController
  # GET /tracks
  # GET /tracks.json
  
  
     before_filter :authenticate_user!, :except => [:show]
  def index
    @tracks = Track.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @tracks }
    end
  end

  # GET /tracks/1
  # GET /tracks/1.json
  def show
   # @track = Track.find(params[:id])
    @geocach = Geocach.where(:random_code => params[:id]).last
    
 
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @track }
    end
  end

  # GET /tracks/new
  # GET /tracks/new.json
  def new
    @track = Track.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @track }
    end
  end

  # GET /tracks/1/edit
  def edit
    @track = Track.find(params[:id])
  end

  # POST /tracks
  # POST /tracks.json
  def create
    @track = Track.new(params[:track])

    respond_to do |format|
      if @track.save
        format.html { redirect_to @track, notice: 'Track was successfully created.' }
        format.json { render json: @track, status: :created, location: @track }
      else
        format.html { render action: "new" }
        format.json { render json: @track.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /tracks/1
  # PUT /tracks/1.json
  def update
    @track = Track.find(params[:id])

    respond_to do |format|
      if @track.update_attributes(params[:track])
        format.html { redirect_to @track, notice: 'Track was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @track.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tracks/1
  # DELETE /tracks/1.json
  def destroy
    @track = Track.find(params[:id])
    @track.destroy

    respond_to do |format|
      format.html { redirect_to tracks_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/tracks_helper.rb
module TracksHelper
end

app/views/tracks/_form.html.erb
<%= simple_form_for @track, :html => { :class => 'form-horizontal' } do |f| %>
  <%= f.input :name %>
  <div class="form-actions">
    <%= f.button :submit, :class => 'btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                tracks_path, :class => 'btn' %>
  </div>
<% end %>

app/views/tracks/edit.html.erb
<%- model_class = Track -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/tracks/index.html.erb
<%- model_class = Track -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @tracks.each do |track| %>
      <tr>
        <td><%= link_to track.id, track_path(track) %></td>
        <td><%= track.name %></td>
        <td><%=l track.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_track_path(track), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      track_path(track),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_track_path,
            :class => 'btn btn-primary' %>

app/views/tracks/new.html.erb
<%- model_class = Track -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/tracks/show.html.erb
<%- model_class = Geocach -%>
<div class="page-header">
	
	<% unless @geocach.blank? %>
 

	
  <h1>Congratulations  - You have found <%= @geocach.cache_name.capitalize %></h1>
</div>

<p>
	<strong>
This cache has been found 33 times now  
</strong>
</p>

Sign up to set up your our talking geocaches click here
<p>
	
	</p>
<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @geocach.name %></dd>
 
 
 

<% unless @geocach.lat.blank? %>
  <dt><strong>lat:</strong></dt>
  <dd><%= @geocach.lat  %></dd>
<%end%>

<% unless @geocach.lad.blank? %>
  <dt><strong>lad:</strong></dt>
  <dd><%= @geocach.lad  %></dd>
<%end%>


<% unless @geocach.hide.blank? %>
  <dt><strong>This Cache was hid:</strong></dt>
  <dd><%= @geocach.hide  %></dd>
<%end%>

<% unless @geocach.found.blank? %>
  <dt><strong>Times Found:</strong></dt>
  <dd><%= @geocach.found  %></dd>
<%end%>

 
</dl>

	<%else%>
	
	<p>
		Sorry
		</p>
	<%end%>
 