config/routes.rb
BenGeocachingApp::Application.routes.draw do
  resources :tracks


  resources :geocaches


  authenticated :user do
    root :to => 'geocaches#index'
  end
  root :to => "home#index"
  devise_for :users
  resources :users
end

app/models/geocach.rb
class Geocach < ActiveRecord::Base
    include Tokenable
  attr_accessible :cache_name, :email, :found, :random_code, :qr_code, :hide, :image, :lad, :lat, :name, :receive_email, :user_id

  def qr_name
    "#{ENV['URL']} #{self.random_code}"
     
  end

end

app/controllers/geocaches_controller.rb
class GeocachesController < ApplicationController
  # GET /geocaches
  # GET /geocaches.json
  def index
 #   @geocaches = Geocach.all
    @user = current_user.id
    @geocaches = Geocach.where(:user_id => @user)
    

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @geocaches }
    end
  end

  # GET /geocaches/1
  # GET /geocaches/1.json
  def show
    @geocach = Geocach.find(params[:id])
     qr_code = "#{ENV['URL']}#{@geocach.random_code}"
    @qr = RQRCode::QRCode.new( qr_code.to_s , :size => 10, :level => :h )

    
    @qr_code = "#{ENV['URL']}#{@geocach.random_code}"
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @geocach }
      format.png  { render :qrcode => qr_code, :size => 10, :level => :h }
      format.gif  { render :qrcode => qr_code, :size => 10, :level => :h  }
      format.jpeg { render :qrcode => qr_code, :size => 10, :level => :h }
    end
  end

  # GET /geocaches/new
  # GET /geocaches/new.json
  def new
 #   @geocach = Geocach.new
    @geocach = Geocach.new(:user_id => params[:user_id])


    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @geocach }
    end
  end

  # GET /geocaches/1/edit
  def edit
    @geocach = Geocach.find(params[:id])
  end

  # POST /geocaches
  # POST /geocaches.json
  def create
    @geocach = Geocach.new(params[:geocach])

    respond_to do |format|
      if @geocach.save
        format.html { redirect_to @geocach, notice: 'A Geocache was successfully created.' }
        format.json { render json: @geocach, status: :created, location: @geocach }
      else
        format.html { render action: "new" }
        format.json { render json: @geocach.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /geocaches/1
  # PUT /geocaches/1.json
  def update
    @geocach = Geocach.find(params[:id])

    respond_to do |format|
      if @geocach.update_attributes(params[:geocach])
        format.html { redirect_to @geocach, notice: 'This Geocache was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @geocach.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /geocaches/1
  # DELETE /geocaches/1.json
  def destroy
    @geocach = Geocach.find(params[:id])
    @geocach.destroy

    respond_to do |format|
      format.html { redirect_to geocaches_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/geocaches_helper.rb
module GeocachesHelper
end

app/views/geocaches/_form.html.erb
<div class=" block2">
	<br>


<%= simple_form_for @geocach, :html => { :class => 'form-horizontal' } do |f| %>
<%= f.input :user_id, :as => :hidden, :input_html => { :value => current_user.id   } %>
 <%= f.input :cache_name %>
  <%= f.input :lat %>
  <%= f.input :lad %>
  <%= f.input :receive_email %>

  <%= f.input :hide, :label=>"Hid on:" %>
  <div class="pull-center">
    <%= f.button :submit, "Submit Changes",  :class => 'btn-primary btn-flat-small' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                geocaches_path, :class => 'btn btn-flat-small btn-info' %>
 </div>
<% end %>
	<br>
		<br>
			<br>
 </div>

app/views/geocaches/edit.html.erb
<%- model_class = Geocach -%>
<div class="page-header">
  <h1>Edit GeoCache</h1>
</div>
<%= render :partial => 'form' %>

app/views/geocaches/index.html.erb
<%- model_class = Geocach -%>
<div class="page-header">
  <h1>Your GeoCaches</h1>
</div>

<div class="block-sm block">
	
	
<%= link_to t('.new', :default => t("helpers.links.create")),
            new_geocach_path,
            :class => 'btn btn-primary btn-flat-small' %>

<br>
<br>
<table class="table">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:cache_name) %></th>
      <th><%= model_class.human_attribute_name(:hide) %></th>
      <th><%= model_class.human_attribute_name(:found) %></th>
      <th>Hid:</th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @geocaches.each do |geocach| %>
      <tr>
        <td><%= link_to geocach.id, geocach_path(geocach) %></td>
        <td><%= geocach.cache_name %></td>
        <td><%= geocach.hide %></td>
        <td><%= geocach.found %></td>

			  
        <td><%= time_ago_in_words(geocach.created_at) %>  ago </td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_geocach_path(geocach), :class => 'btn btn-primary btn-flat-medium ' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      geocach_path(geocach),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-danger btn-flat-medium ' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>

app/views/geocaches/new.html.erb
<%- model_class = Geocach -%>
	<br>
<div class="page-header">
  <h1>Create New GeoCache</h1>
</div>

<%= render :partial => 'form' %>

app/views/geocaches/show.html.erb
<%- model_class = Geocach -%>
<div class="page-header">
  <h1>GeoCache - <%= @geocach.cache_name.capitalize %></h1>
</div>
 

<div class="block-sm block">
	<br>
 
<dl class="dl-horizontal">
 
<% unless @geocach.lat.blank? %>
  <dt><strong>lat:</strong></dt>
  <dd><%= @geocach.lat  %></dd>
<%end%>

<% unless @geocach.lad.blank? %>
  <dt><strong>lad:</strong></dt>
  <dd><%= @geocach.lad  %></dd>
<%end%>

 
<% unless @geocach.hide.blank? %>
  <dt><strong>Hid On:</strong></dt>
  <dd><%= @geocach.hide  %></dd>
<%end%>

<% unless @geocach.found.blank? %>
  <dt><strong>Times Found:</strong></dt>
  <dd><%= @geocach.found  %></dd>
<%end%>
 <dt><strong>Random Code:</strong></dt>
 <dd><%= @geocach.random_code  %></dd>
 
</dl> 
 
 
  <%= link_to t('.back', :default => t("helpers.links.back")),
              geocaches_path, :class => 'btn btn-flat btn-info'   %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_geocach_path(@geocach), :class => 'btn btn-flat btn-primary' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              geocach_path(@geocach),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger btn-flat' %>
</div>